/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author mayurshiroya
 */
public class MainJFrame extends javax.swing.JFrame {
     PersonDirectory pDirectory;
     
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
         pDirectory = new PersonDirectory();
         initComponents();
         
         generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        profileContainer = new javax.swing.JPanel();
        lblTITLE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(255, 204, 204));

        btnCreate.setText("Create Profile");
        btnCreate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnManage.setText("Manage Profile");
        btnManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });

        btnSearch.setText("Search a Profile");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate)
                    .addComponent(btnManage)
                    .addComponent(btnSearch))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        leftPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreate, btnManage, btnSearch});

        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnCreate)
                .addGap(18, 18, 18)
                .addComponent(btnManage)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(444, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(leftPanel);

        profileContainer.setBackground(new java.awt.Color(153, 153, 255));
        profileContainer.setLayout(new java.awt.CardLayout());

        lblTITLE.setBackground(new java.awt.Color(153, 153, 255));
        lblTITLE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTITLE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTITLE.setText("Person Profile");
        lblTITLE.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        profileContainer.add(lblTITLE, "card2");

        splitPane.setRightComponent(profileContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
       CreateJPanel panel=new CreateJPanel(profileContainer,pDirectory);
       profileContainer.add("CreateJPanel",panel);// TODO add your handling code here:
       CardLayout layout = (CardLayout) profileContainer.getLayout();
       layout.next(profileContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
       ManageProfileJPanel panel=new ManageProfileJPanel(profileContainer,pDirectory);
       profileContainer.add("ManageProfileJPanel",panel);// TODO add your handling code here:
       CardLayout layout = (CardLayout) profileContainer.getLayout();
       layout.next(profileContainer); 
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       SearchJPanel panel=new SearchJPanel(profileContainer,pDirectory);
       profileContainer.add("SearchJPanel",panel);
       CardLayout layout = (CardLayout) profileContainer.getLayout();
       layout.next(profileContainer);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblTITLE;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel profileContainer;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
        Address home1 = new Address("123 Main St", "Unit 1", "Boston", "MA", "02115", "555-1234");
        Address work1 = new Address("456 Work Pl", "Unit 9", "Cambridge", "MA", "02139", "555-5678");
        Person p1 = new Person("John", "Doe", 'M', 30, 5.9f, 70.5, "123-45-6789", home1, work1);

        Address home2 = new Address("321 Main St", "Unit 2", "New York", "NY", "02116", "555-5678");
        Address work2 = new Address("789 Work Pl", "Unit 10", "New York", "NY", "02199", "555-5678");
        Person p2 = new Person("Liu", "Su", 'G', 20, 4.9f, 56.5, "333-56-6889", home2, work2);
        
        Address home3 = new Address("123 Tremont St", "Unit 4", "Chicago", "IL", "02115", "555-1234");
        Address work3 = new Address("456 Tremont Pl", "Unit 5", "Chicago", "IL", "02139", "555-0000");
        Person p3 = new Person("Jane", "Williams", 'M', 30, 5.9f, 66.5, "123-45-6789", home3, work3);
        
        Address home4 = new Address("123 South St", "Unit 1", "Boston", "MA", "02115", "555-1234");
        Address work4 = new Address("456 South Pl", "Unit 9", "Boston", "MA", "02139", "555-5678");
        Person p4 = new Person("Bob", "Smith", 'M', 30, 5.9f, 70.5, "123-45-6789", home4, work4);
        
        Address home5 = new Address("123 Main St", "Unit 11", "San Diego", "CA", "02115", "555-1234");
        Address work5 = new Address("456 Work Pl", "Unit 34", "San Diego", "CA", "02139", "555-5678");
        Person p5 = new Person("Jensy", "Doe", 'M', 30, 5.9f, 70.5, "123-45-6789", home5, work5);
        
        Address home6 = new Address("123 Main St", "Unit 1", "Boston", "MA", "02115", "555-1234");
        Address work6 = new Address("456 Work Pl", "Unit 9", "Cambridge", "MA", "02139", "555-5678");
        Person p6 = new Person("Harry", "Potter", 'M', 30, 5.9f, 70.5, "123-45-6789", home6, work6);
        
        pDirectory.addPerson(p1);
        pDirectory.addPerson(p2);
        pDirectory.addPerson(p3);
        pDirectory.addPerson(p4);
        pDirectory.addPerson(p5);
        pDirectory.addPerson(p6);
    }
    
}
