/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import model.Address;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author mayurshiroya
 */
public class SearchJPanel extends javax.swing.JPanel {
     
     JPanel profileContainer;
     PersonDirectory pdirectory;
     Person person;
    /**
     * Creates new form SearchJPanel
     */
    public SearchJPanel(JPanel container, PersonDirectory directory) {
        profileContainer=container;
        pdirectory=directory;
        initComponents();
        
        if (person != null) {
        refreshTextFields();
    }
        
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lbltop = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblCity1 = new javax.swing.JLabel();
        txtMinitial = new javax.swing.JTextField();
        lblZIP1 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtStreet1 = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtCity1 = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtZIP1 = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        lblUnit1 = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        lblHome = new javax.swing.JLabel();
        lblState1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        txtUnit1 = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtState1 = new javax.swing.JTextField();
        lblZIP = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtZIP = new javax.swing.JTextField();
        lblUnit = new javax.swing.JLabel();
        lalfname = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblLname = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtUnit = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        lblMinitial = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        lblWork = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        lblStreet1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lbltop.setBackground(new java.awt.Color(255, 255, 255));
        lbltop.setText("Type Name or Street Address");
        lbltop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });

        lblCity1.setText("City");

        lblZIP1.setText("ZIP Code");

        txtCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCity1ActionPerformed(evt);
            }
        });

        lblSSN.setText("SSN");

        lblUnit1.setText("Unit Number");

        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setText("Home Address");
        lblHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblState1.setText("State");

        lblPhone1.setText("Phone Number");

        lblStreet.setText("Street Address");

        lblCity.setText("City");

        txtState1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtState1ActionPerformed(evt);
            }
        });

        lblZIP.setText("ZIP Code");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblUnit.setText("Unit Number");

        lalfname.setText("First Name");

        lblState.setText("State");

        lblLname.setText("Last Name");

        lblPhone.setText("Phone Number");

        lblAge.setText("Age");

        lblHeight.setText("Height");

        lblMinitial.setText("Middle Initial");

        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        lblWeight.setText("Weight");

        lblWork.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWork.setText("Work Address");
        lblWork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblStreet1.setText("Street Address");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblZIP)
                        .addGap(28, 28, 28)
                        .addComponent(txtZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStreet)
                            .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStreet1)
                            .addComponent(lblCity1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUnit)
                                    .addComponent(lblState, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhone)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUnit1)
                                    .addComponent(lblState1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPhone1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdate)
                                    .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lalfname)
                                .addComponent(lblLname, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblMinitial)
                            .addComponent(lblSSN))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMinitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge)
                                    .addComponent(lblHeight)
                                    .addComponent(lblWeight))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblZIP1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addComponent(txtZIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbltop)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblWork, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAge, txtCity, txtCity1, txtHeight, txtLname, txtMinitial, txtPhone, txtPhone1, txtState, txtState1, txtStreet, txtStreet1, txtUnit, txtUnit1, txtWeight, txtZIP, txtZIP1, txtfname, txtssn});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lalfname, lblAge, lblCity, lblCity1, lblHeight, lblLname, lblMinitial, lblPhone, lblPhone1, lblSSN, lblState, lblState1, lblStreet, lblStreet1, lblUnit, lblUnit1, lblWeight, lblZIP, lblZIP1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lalfname)
                    .addComponent(lblAge)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLname)
                    .addComponent(lblHeight)
                    .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinitial)
                    .addComponent(lblWeight)
                    .addComponent(txtMinitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUnit)
                            .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblState)
                            .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreet)
                            .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZIP)
                            .addComponent(txtZIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(lblWork, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreet1)
                            .addComponent(txtStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity1)
                            .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblZIP1)
                            .addComponent(txtZIP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUnit1)
                            .addComponent(txtUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblState1)
                            .addComponent(txtState1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone1)
                            .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         if(!txtSearch.getText().isBlank()){
           
            String searchValue = txtSearch.getText();
            searchPerson(searchValue);
         }
        else{
        JOptionPane.showMessageDialog(null,"Please type name or address to view","Warning",JOptionPane.WARNING_MESSAGE);
        }
         
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCity1ActionPerformed

    private void txtState1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtState1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtState1ActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        setEditMode();  // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int age;
        float height;
        double weight;
        char mname = 0;
        
        String fname=txtfname.getText();
        String lname=txtLname.getText();
        String ssn=txtssn.getText();
        String street=txtStreet.getText();
        String unitnum=txtUnit.getText();
        String city=txtCity.getText();
        String state=txtState.getText();
        String zip=txtZIP.getText();
        String phone=txtPhone.getText();
        String street1=txtStreet1.getText();
        String unitnum1=txtUnit1.getText();
        String city1=txtCity1.getText();
        String state1=txtState1.getText();
        String zip1=txtZIP1.getText();
        String phone1=txtPhone1.getText();
        
        
        if(fname.isBlank()||lname.isBlank()||ssn.isBlank()||street.isBlank()||unitnum.isBlank()||city.isBlank()||state.isBlank()||zip.isBlank()|
                phone.isBlank()||street1.isBlank()||unitnum1.isBlank()||city1.isBlank()||state1.isBlank()||zip1.isBlank()||phone1.isBlank()){
        
            JOptionPane.showMessageDialog(this,"All fields are mandatory","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (txtMinitial.getText().isEmpty()) {
   
            JOptionPane.showMessageDialog(null, "Please enter a middle initial.");
        }
        else if (txtMinitial.getText().length() > 1) {
    
              JOptionPane.showMessageDialog(null, "Middle initial must be a single character.");
        }
        else {
    
        mname = txtMinitial.getText().charAt(0);
   
        }
        
        try{
        age=Integer.parseInt(txtAge.getText());
        height=Float.parseFloat(txtHeight.getText());
        weight=Double.parseDouble(txtWeight.getText());
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,"Please check the input for age, height and weight,","Warning",JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        
        Address home = new Address(street,unitnum,city,state,zip,phone);
        Address work = new Address(street1,unitnum1,city1,state1,zip1,phone1);
        
        person.setfName(fname);
        person.setLname(lname);
        person.setMiddleInitial(mname);
        person.setSsn(ssn);
        person.setAge(age);
        person.setHeight(height);
        person.setWeight(weight);
        person.setHomeAddress(home);
        person.setWorkAddress(work);
        
        JOptionPane.showMessageDialog(null,"Account Successfully Updated","Warning",JOptionPane.WARNING_MESSAGE);
        
        setViewMode();
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lalfname;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblMinitial;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblState1;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblStreet1;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JLabel lblUnit1;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWork;
    private javax.swing.JLabel lblZIP;
    private javax.swing.JLabel lblZIP1;
    private javax.swing.JLabel lbltop;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMinitial;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtState1;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtStreet1;
    private javax.swing.JTextField txtUnit;
    private javax.swing.JTextField txtUnit1;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZIP;
    private javax.swing.JTextField txtZIP1;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtssn;
    // End of variables declaration//GEN-END:variables

   
    private void searchPerson(String searchValue) {
        person = null;

        person = pdirectory.searchByFirstName(searchValue);
   
        if (person == null) {
            person = pdirectory.searchByLastName(searchValue);
        }

        if (person == null) {
            person = pdirectory.searchByStreetAddress(searchValue);
        }
        
        if (person != null){
            
           txtfname.setText(person.getfName());
        txtLname.setText(person.getLname());
        txtssn.setText(person.getSsn());
        txtMinitial.setText(String.valueOf(person.getMiddleInitial()));
        txtStreet.setText(person.getHomeAddress().getState());
        txtUnit.setText(person.getHomeAddress().getAptnum());
        txtCity.setText(person.getHomeAddress().getCity());
        txtState.setText(person.getHomeAddress().getState());
        txtZIP.setText(person.getHomeAddress().getZip());
        txtPhone.setText(person.getHomeAddress().getPhone());
        txtStreet1.setText(person.getWorkAddress().getStreetadd());
        txtUnit1.setText(person.getWorkAddress().getAptnum());
        txtCity1.setText(person.getWorkAddress().getCity());
        txtState1.setText(person.getWorkAddress().getState());
        txtZIP1.setText(person.getWorkAddress().getZip());
        txtPhone1.setText(person.getWorkAddress().getPhone());
        txtAge.setText(String.valueOf(person.getAge()));
        txtHeight.setText(String.valueOf(person.getHeight()));
        txtWeight.setText(String.valueOf(person.getWeight()));
        }
        
        else {
             JOptionPane.showMessageDialog(null,"No match Found","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void refreshTextFields() {
        if (person == null) {
        System.out.println("Person object is null. Skipping field population.");
        return;
    }
        txtfname.setText(person.getfName());
        txtLname.setText(person.getLname());
        txtssn.setText(person.getSsn());
        txtMinitial.setText(String.valueOf(person.getMiddleInitial()));
        txtStreet.setText(person.getHomeAddress().getState());
        txtUnit.setText(person.getHomeAddress().getAptnum());
        txtCity.setText(person.getHomeAddress().getCity());
        txtState.setText(person.getHomeAddress().getState());
        txtZIP.setText(person.getHomeAddress().getZip());
        txtPhone.setText(person.getHomeAddress().getPhone());
        txtStreet1.setText(person.getWorkAddress().getStreetadd());
        txtUnit1.setText(person.getWorkAddress().getAptnum());
        txtCity1.setText(person.getWorkAddress().getCity());
        txtState1.setText(person.getWorkAddress().getState());
        txtZIP1.setText(person.getWorkAddress().getZip());
        txtPhone1.setText(person.getWorkAddress().getPhone());
        txtAge.setText(String.valueOf(person.getAge()));
        txtHeight.setText(String.valueOf(person.getHeight()));
        txtWeight.setText(String.valueOf(person.getWeight()));
    }

    private void setViewMode() {
                txtfname.setEnabled(false);
        txtLname.setEnabled(false);
        txtssn.setEnabled(false);
        txtMinitial.setEnabled(false);
        txtStreet.setEnabled(false);
        txtUnit.setEnabled(false);
        txtCity.setEnabled(false);
        txtState.setEnabled(false);
        txtZIP.setEnabled(false);
        txtPhone.setEnabled(false);
        txtStreet1.setEnabled(false);
        txtUnit1.setEnabled(false);
        txtCity1.setEnabled(false);
        txtState1.setEnabled(false);
        txtZIP1.setEnabled(false);
        txtPhone1.setEnabled(false);
        txtAge.setEnabled(false);
        txtHeight.setEnabled(false);
        txtWeight.setEnabled(false);
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
        
    }

    private void setEditMode() {
         txtfname.setEnabled(true);
        txtLname.setEnabled(true);
        txtssn.setEnabled(true);
        txtMinitial.setEnabled(true);
        txtStreet.setEnabled(true);
        txtUnit.setEnabled(true);
        txtCity.setEnabled(true);
        txtState.setEnabled(true);
        txtZIP.setEnabled(true);
        txtPhone.setEnabled(true);
        txtStreet1.setEnabled(true);
        txtUnit1.setEnabled(true);
        txtCity1.setEnabled(true);
        txtState1.setEnabled(true);
        txtZIP1.setEnabled(true);
        txtPhone1.setEnabled(true);
        txtAge.setEnabled(true);
        txtHeight.setEnabled(true);
        txtWeight.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }
}
